### ISSUE TITLE
Order Edit - Edit Create Date

### ISSUE THREAD

**Issue by saliozzia** [loadedcommerce/loaded6#1]
allow a way to edit the date of an order

**Comment by wa4u** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/3207057/7946911/3dee70ae-0997-11e5-8fb9-748dc95814cf.png)

**Comment by saliozzia** [comment]
looks good.

now to test it

**Comment by wa4u** [comment]
Added to CE, Pro and B2B.

**Comment by saliozzia** [comment]
This issue was moved to loadedcommerce/Loaded6CE#16
